@echo off
:: ===== WINDOWS CLIENT =====
set WIN10_PRO=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
set WIN11_PRO=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX

:: ===== WINDOWS SERVER =====
set WS2019_STD=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
set WS2022_STD=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX

:: ===== OFFICE =====
set O2019_PROPLUS=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
set O2021_PROPLUS=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX